### ISSUE TITLE
[PostgreSQL] Error "Unsupported type _BPCHAR"

### ISSUE THREAD

**Issue by morihaya** [embulk/embulk-input-jdbc#142]
Hi there.
I faced error `Unsupported type _BPCHAR` when used embulk-imput-postgresql.
I guess this cause is [PostgreSQL Array Types](https://www.postgresql.org/docs/9.6/static/arrays.html).
Does anyone know it?

# Versions
* embulk (0.9.4)
* embulk-input-postgresql (0.9.1)
* embulk-output-postgresql (0.8.0)
* In: PostgreSQL (9.6.6) (AWS RDS PostgreSQL)
* Out: PostgreSQL (9.6.3) (AWS RDS Aurora PostgreSQL)

# Table DDL
```
CREATE TABLE postgres.meisai (
    version_id smallint,
    version character(4),
    shouhin_id character(8)[],
    pg_created_at timestamp without time zone,
    pg_updated_at timestamp without time zone
);
```

# Embulk liquid file

```yaml
in:
  type: postgresql
  host: rdspg
  user: postgres
  password: hogehoge
  database: postgres
  schema: postgres
  table: meisai
  options: {useLegacyDatetimeCode: false, serverTimezone: Asia/Tokyo}
  default_timezone: Asia/Tokyo
  where: "pg_updated_at > to_timestamp('{{ env.get_time }}', 'YYYY-MM-DD HH24:MI:SS')"
  column_options:
    version_id: { type: long }
    version: { type: string }
    shouhin_id: { type: string , value_type: array }
    pg_created_at: { type: timestamp , format: '%Y-%m-%d %H:%M:%S' }
    pg_updated_at: { type: timestamp , format: '%Y-%m-%d %H:%M:%S' }
out:
  type: postgresql
  host: rdsaurorapg
  user: postgres
  password: hogehoge
  database: postgres
  schema: postgres
  table: meisai
  options: {useLegacyDatetimeCode: false, serverTimezone: Asia/Tokyo}
  default_timezone: Asia/Tokyo
  mode: merge
  column_options:
    version_id: { type: smallint }
    version: { type: character(4) }
    shouhin_id: { type: json }
    pg_created_at: { type: timestamp without time zone }
    pg_updated_at: { type: timestamp without time zone }
```

# Error message
```
2018-06-05 10:12:30.693 +0900 [INFO] (0001:transaction): SQL: CREATE TABLE "postgres"."meisai_00000163cd80a6e4_embulk000" ("version_id" smallint, "version" character(4), "shouhin_id" json, "pg_created_at" timestamp without time zone, "pg_updated_at" timestamp without time zone)
2018-06-05 10:12:30.704 +0900 [INFO] (0001:transaction): > 0.01 seconds
org.embulk.exec.PartialExecutionException: java.lang.UnsupportedOperationException: Unsupported type _BPCHAR (sqlType=2003, size=255, scale=0)
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:548)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:162)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:437)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:92)
	at org.embulk.cli.Main.main(Main.java:26)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:445)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:385)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:382)
		at org.embulk.spi.Exec.doWith(Exec.java:22)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:382)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:165)
		... 5 more
Caused by: java.lang.UnsupportedOperationException: Unsupported type _BPCHAR (sqlType=2003, size=255, scale=0)
	at org.embulk.output.jdbc.setter.ColumnSetterFactory.unsupportedOperationException(ColumnSetterFactory.java:206)
	at org.embulk.output.jdbc.setter.ColumnSetterFactory.newCoalesceColumnSetter(ColumnSetterFactory.java:188)
	at org.embulk.output.postgresql.setter.PostgreSQLColumnSetterFactory.newCoalesceColumnSetter(PostgreSQLColumnSetterFactory.java:26)
	at org.embulk.output.jdbc.setter.ColumnSetterFactory.newColumnSetter(ColumnSetterFactory.java:42)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.newColumnSetters(AbstractJdbcOutputPlugin.java:780)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.doBegin(AbstractJdbcOutputPlugin.java:588)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$2.run(AbstractJdbcOutputPlugin.java:445)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$RetryableSQLExecution.call(AbstractJdbcOutputPlugin.java:1239)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$RetryableSQLExecution.call(AbstractJdbcOutputPlugin.java:1227)
	at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:81)
	at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:62)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:1212)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:1204)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.begin(AbstractJdbcOutputPlugin.java:439)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:415)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:503)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:50)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:498)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
	at org.embulk.spi.util.Filters.transaction(Filters.java:42)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:493)
	at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:200)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:489)
	... 11 more

Error: java.lang.UnsupportedOperationException: Unsupported type _BPCHAR (sqlType=2003, size=255, scale=0)
2018-06-05 10:12:30.775 +0900 [ERROR] (0554@[0:develop]+main_batchdb_to_sanshodb+sub1_postgre^sub+data_load^sub+for-0=table=0=analytic) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
	at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-06-05 10:12:31.455 +0900 [INFO] (0554@[0:develop]+main_batchdb_to_sanshodb^failure-alert) io.digdag.core.agent.OperatorManager: type: notify
```

**Comment by morihaya** [comment]
Hello, @hiroyuki-sato 
Thank you for your reply.
I tried some cases, but all failed ...

# Case1

in
    shouhin_id: { type: json , value_type: json }
out
    shouhin_id: { type: json }

```
org.embulk.exec.PartialExecutionException: java.lang.UnsupportedOperationException: Unsupported type _BPCHAR (sqlType=2003, size=255, scale=0)
```

# Case2

in
  shouhin_id: { type: json , value_type: json }
out
  shouhin_id: { type: character(8) , value_type: json }

```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: column "shouhin_id" is of type character[] but expression is of type character
  Hint: You will need to rewrite or cast the expression.
  Position: 652
```

# Case3
in
  shouhin_id: { type: json , value_type: json }
out
  shouhin_id: { type: json , value_type: json }

```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: column "shouhin_id" is of type character[] but expression is of type json
  Hint: You will need to rewrite or cast the expression.
  Position: 652
```

# Case4
in
  shouhin_id: { type: string , value_type: array }
out
 shouhin_id: { type: json , value_type: json }

```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: column "shouhin_id" is of type character[] but expression is of type json
  Hint: You will need to rewrite or cast the expression.
  Position: 652
```

# Case5  
in
  shouhin_id: { type: string , value_type: array }
out
  shouhin_id: { type: character(8) , value_type: json }

```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: column "shouhin_id" is of type character[] but expression is of type character
  Hint: You will need to rewrite or cast the expression.
  Position: 652
```

# Case6
in
    shouhin_id: { type: string , value_type: array }
out
    shouhin_id: { type: json }

```
org.embulk.exec.PartialExecutionException: java.lang.UnsupportedOperationException: Unsupported type _BPCHAR (sqlType=2003, size=255, scale=0)
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
```

**Comment by hiroyuki-sato** [comment]
I'm not familiar array column in PostgreSQL.
It seems that `character(8)[]` data import well in my environment.
This is my test result.
https://github.com/hiroyuki-sato/embulk-support/tree/master/input-jdbc_142_import_json_to_pg

* Does AWS Aurora with PostgreSQL support json column?
* Do you want to load input data into the same table? (Input and output table name are same). Can you change it?

**Comment by morihaya** [comment]
Thank you for your test.

>* Does AWS Aurora with PostgreSQL support json column?

Yes. I created a table with the same ddl and made it successful.
And i checked AWS document for [aurora postgres](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html).

> * Do you want to load input data into the same table? (Input and output table name are same). Can you change it?

Yes, I load it on the same table.
And i do not want to change the table name.


I feel your support again.
I will do a little more testing.

**Comment by hiroyuki-sato** [comment]
Hello, @morihaya 

Oh, I see. I can reproduce your issue in my environment.

embulk-ouput-postgresql plugin can't create intermediate table if the destination table schema as follows. So, This is not embulk-input-postgresql issue.


```
\d meisai
                  Table "public.meisai"
    Column     |            Type             | Modifiers
---------------+-----------------------------+-----------
 version_id    | smallint                    |
 version       | character(4)                |
 shouhin_id    | character(8)[]              |
 pg_created_at | timestamp without time zone |
 pg_updated_at | timestamp without time zone |
```

The plugin tries to create an intermediate table with the following SQL

```sql
CREATE TABLE "public"."meisai_00000163cfdc3c70_embulk003" (
  "version_id" INT2,
  "version" BPCHAR,
  "shouhin_id" _BPCHAR,
  "pg_created_at" TIMESTAMP,
  "pg_updated_at" TIMESTAMP
)
```

And raise the following exception

```
org.embulk.exec.PartialExecutionException: java.lang.UnsupportedOperationException: Unsupported type _BPCHAR (sqlType=2003, size=8, scale=0)
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:339)
```

`_BPCHAR` is `character(8)[]` column. It seems that plugin can't get correct data if the column is `character(8)[]`.

**Comment by hiroyuki-sato** [comment]
Hello, @morihaya 

Could you close this issue? I created https://github.com/embulk/embulk-output-jdbc/issues/232
