### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by diegotejadav** [embulk/embulk-input-jdbc#144]
Hi, I'm getting this error when trying to read data from an **Oracle Database 11g Release 11.2.0.2.0 - 64bit Production**:

```sh
DLTV:embulk diegotejadav$ embulk preview clientes_load.yml
2018-08-14 08:32:10.730 -0500: Embulk v0.9.7
2018-08-14 08:32:11.561 -0500 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2018-08-14 08:32:14.201 -0500 [INFO] (main): Gem's home and path are set by default: "/Users/diegotejadav/.embulk/lib/gems"
2018-08-14 08:32:14.970 -0500 [INFO] (main): Started Embulk v0.9.7
2018-08-14 08:32:15.064 -0500 [INFO] (0001:preview): Loaded plugin embulk-input-oracle (0.9.3)
2018-08-14 08:32:15.111 -0500 [INFO] (0001:preview): Connecting to jdbc:oracle:thin:@IP.ADDRESS:1521/DBNAME options {oracle.jdbc.ReadTimeout=1800000, user=USERNAME, password=***, oracle.net.CONNECT_TIMEOUT=300000}
java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V
        at org.embulk.input.oracle.OracleInputConnection.setSearchPath(OracleInputConnection.java:20)
        at org.embulk.input.jdbc.JdbcInputConnection.<init>(JdbcInputConnection.java:52)
        at org.embulk.input.oracle.OracleInputConnection.<init>(OracleInputConnection.java:14)
        at org.embulk.input.OracleInputPlugin.newConnection(OracleInputPlugin.java:127)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:197)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:118)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:106)
        at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:29)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:73)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:70)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:70)
        at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:151)
        at org.embulk.EmbulkRunner.previewInternal(EmbulkRunner.java:215)
        at org.embulk.EmbulkRunner.preview(EmbulkRunner.java:107)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:433)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
        at org.embulk.cli.Main.main(Main.java:26)

Error: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V
```

My seed file:
```yml
in:
  type: oracle  
  driver_path: /path/to/downloaded/ojdbc6.jar
  url: jdbc:oracle:thin:@IP.ADDRESS:1521/DBNAME
  user: <user>
  password: <password>
  query:
    SELECT * FROM SQUEMA.TABLE WHERE ROWNUM < 20
out:
  type: stdout
```

What I am missing?
I have tested the connection credentials to that database with other clients and it works.

Thanks!

**Comment by diegotejadav** [comment]
Finally the solution was to use the [ojdbc7.jar driver](https://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html) not the ojdbc6.jar as the DB versión suggested.
