### ISSUE TITLE
is it possible to access record?

### ISSUE THREAD

**Issue by makkaba** [embulk/embulk-input-jdbc#145]
i am using embulk for transferring new data from mssql(source) to mysql(destin) periodically.

then I want to get `id` column from  the *last* record after getting all data from source database.

it is to mark down the last id value as a "i read data until this index" sign. 

is there any solution to get access with any record while reading?

thanks.

**Comment by hiroyuki-sato** [comment]
Hello, @makkaba 

Could you try [Incremental loading](https://github.com/embulk/embulk-input-jdbc/tree/master/embulk-input-mysql#incremental-loading)?

If you execute `embulk run -c diff.yml conf.yml` command, It store last record in `diff.yml`.
(Ref: [Loading a CSV file](http://www.embulk.org/docs/recipe/scheduled-csv-load-to-elasticsearch-kibana5.html#loading-a-csv-file))

**Comment by makkaba** [comment]
thanks for guide
but when i try to incremental loading, 
it throws an error.

Error: org.embulk.config.ConfigException: 'incremental_columns' and 'last_record' parameters are not supported if 'query' parameter is set.

even i heard it is resolved, but doesn't work. 
https://github.com/embulk/embulk-input-jdbc/pull/143

i am trying to figure it out reason.
embulk version 0.9.4

**Comment by sakama** [comment]
@makkaba What version of embulk-input-sqlserver are you using?
Could you also provide full stacktrace?

**Comment by makkaba** [comment]
sure.
then i think it must be jdbc version problem.

```
embulk (0.9.4 java)
embulk-input-jdbc (0.9.1)
embulk-input-mysql (0.9.1)
embulk-input-sqlserver (0.9.1)
embulk-output-command (0.1.4)
embulk-output-jdbc (0.7.13)
embulk-output-mysql (0.8.0)
embulk-output-sqlserver (0.8.0)
embulk-parser-jsonl (0.2.0)
```

```
2018-08-20 05:08:47.682 +0000 [INFO] (0001:transaction): Using JDBC Driver 1.3.1
org.embulk.exec.PartialExecutionException: org.embulk.config.ConfigException: 'incremental_columns' and 'last_record' parameters are not supported if 'query' parameter is set.
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:548)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:162)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:437)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:92)
        at org.embulk.cli.Main.main(Main.java:26)
        Suppressed: java.lang.NullPointerException
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:445)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:385)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:382)
                at org.embulk.spi.Exec.doWith(Exec.java:22)
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:382)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:165)
                ... 5 more
Caused by: org.embulk.config.ConfigException: 'incremental_columns' and 'last_record' parameters are not supported if 'query' parameter is set.
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.getRawQuery(AbstractJdbcInputPlugin.java:334)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.setupTask(AbstractJdbcInputPlugin.java:211)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:195)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:489)
        ... 11 more
```

**Comment by makkaba** [comment]
thanks. @hiroyuki-sato @sakama 
it was caused by version.

*for other newbies*: 
pls check `embulk-input-jdbc` version.
with 
```
embulk gem list
```
