### ISSUE TITLE
incremental loading with raw query failure -  java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by kulmam92** [embulk/embulk-input-jdbc#150]
Hi

I'm trying to use incremental loading with raw query. However, it fails with "java.lang.IndexOutOfBoundsException: Index: 1, Size: 1" error.

config file
`{% include 'datasources/in_sqlserver_readonly' %}
  database: tempdb
  query: 
    declare @test int = :database_id
    SELECT name, database_id
     from sys.databases
      where database_id = @test
    order by database_id
  use_raw_query_with_incremental: true
  incremental_columns:
    - database_id
  incremental: true
  last_record: [1]
{% include 'datasources/out_azure_blob' %}
  container: adventureworks
  path_prefix: lead-csv-
  file_ext: csv
  formatter:
    type: csv
    header_line: false`

Full error log
`2018-10-18 21:36:48.310 -0700 [INFO] (0001:transaction): Using JDBC Driver 7.0.0.0
org.embulk.exec.PartialExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:339)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:565)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:34)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:352)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:349)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:349)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:161)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:436)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
        at org.embulk.cli.Main.main(Main.java:26)
        Suppressed: java.lang.NullPointerException
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:462)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:396)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:393)
                at org.embulk.spi.Exec.doWith(Exec.java:22)
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:393)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:164)
                ... 5 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.embulk.input.jdbc.JdbcInputConnection.replacePlaceholder(JdbcInputConnection.java:397)
        at org.embulk.input.jdbc.JdbcInputConnection.wrapIncrementalQuery(JdbcInputConnection.java:307)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.setupTask(AbstractJdbcInputPlugin.java:282)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:201)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:506)
        ... 11 more

Error: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1'

**Comment by sakama** [comment]
Hi

* Does `database_id` column exist in your table?
* How about following query?
  * This feature doesn't use clever parser and might not be able to parse complex query.
  ```yaml
  SELECT name, database_id
    from sys.databases
    where database_id = :database_id
  order by database_id
  ```

**Comment by kulmam92** [comment]
@sakama 
I'm getting the same error.

2018-10-18 22:36:18.197 -0700 [INFO] (main): Started Embulk v0.9.8
2018-10-18 22:36:18.470 -0700 [INFO] (0001:transaction): Loaded plugin embulk-input-sqlserver (0.9.3)
2018-10-18 22:36:18.654 -0700 [INFO] (0001:transaction): Loaded plugin embulk-output-azure_blob_storage (0.1.6)

2018-10-18 22:36:20.589 -0700 [INFO] (0001:transaction): Using JDBC Driver 7.0.0.0
org.embulk.exec.PartialExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:339)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:565)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:34)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:352)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:349)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:349)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:161)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:436)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
        at org.embulk.cli.Main.main(Main.java:26)
        Suppressed: java.lang.NullPointerException
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:462)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:396)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:393)
                at org.embulk.spi.Exec.doWith(Exec.java:22)
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:393)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:164)
                ... 5 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.embulk.input.jdbc.JdbcInputConnection.replacePlaceholder(JdbcInputConnection.java:397)
        at org.embulk.input.jdbc.JdbcInputConnection.wrapIncrementalQuery(JdbcInputConnection.java:307)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.setupTask(AbstractJdbcInputPlugin.java:282)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:201)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:506)
        ... 11 more

Error: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

**Comment by sakama** [comment]
I found temporal solution.
This query should work.

```
SELECT database_id, name
  from sys.databases
  where database_id = :database_id
order by database_id
```
