### ISSUE TITLE
Column type 'long' set at incremental_columns option is not supported

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk-input-jdbc#158]
Getting error 

```
Caused by: org.embulk.spi.DataException: Column type 'long' set at incremental_columns option is not supported
        at org.embulk.input.jdbc.getter.AbstractColumnGetter.encodeToJson(AbstractColumnGetter.java:92)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin$LastRecordStore.accept(AbstractJdbcInputPlugin.java:441)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.run(AbstractJdbcInputPlugin.java:490)
        at org.embulk.spi.util.Executors.process(Executors.java:62)
        at org.embulk.spi.util.Executors.process(Executors.java:38)
        at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:170)
        at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:167)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Error: org.embulk.spi.DataException: Column type 'long' set at incremental_columns option is not supported
```
when using embulk-input-oracle plugin with following config;
```
in:
  type: oracle
  driver_path: /usr/lib/oracle/12.1/client64/lib/ojdbc7.jar
  url: "jdbc:oracle:thin:@oralceurl"
  user: -
  password: -
  table: "table"
  incremental: true
  incremental_columns: [ID]
  column_options:
    ID: {type: long}

**Comment by kakoni** [comment]
Aah, perhaps this is fault on my side.
It seems columns option should be configured using value_type when using incremental column;
```
column_options:
    ID: {value_type: long}
```

So perhaps the error message should be bit different more informative. Closing this.
