### ISSUE TITLE
embulk-input-sqlserver can't connect to db with instance name

### ISSUE THREAD

**Issue by hieudion** [embulk/embulk-input-jdbc#168]
I faced this issue when using the new version of mssql:JDBC 7.2.2.
It runs fine with `jtds:jdbc` but when updates to `mssql:jdbc` i can't connect to the db. DB is on Azure I think.
Just raise the issue here so we can aware of it.
The same thing happened for output.

**Comment by hito4t** [comment]
@hieudion 
I can connect to a local SQL Server with instance name using both jTDS and mssql:jdbc .
Would you show embulk log?

**Comment by hieudion** [comment]
Yah, I checked with local instances before and it worked perfectly. 
Maybe you should try with multiple named instances in Azure.

Here is the log: 
`2019-08-14 12:42:21.536 +0000 [INFO] (main): Started Embulk v0.9.17
2019-08-14 12:42:22.532 +0000 [INFO] (0001:transaction): Start getting object with path: [job_540296086_result]
2019-08-14 12:42:22.815 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=32 / tasks=1
2019-08-14 12:42:22.853 +0000 [INFO] (0001:transaction): Connecting to jdbc:sqlserver://{host_name}\{instance_name};databaseName={database_name} options {user=***, password=***, loginTimeout=300, socketTimeout=1800000}
2019-08-14 12:47:23.745 +0000 [ERROR] (0001:transaction): Operation failed (0:08S01)
2019-08-14 12:47:23.762 +0000 [ERROR] (main): com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host {host_name}, named instance {instance_name} failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host sqlcipprod.database.windows.net, named instance sqlcipprod failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.Exec.doWith(Exec.java:22) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:178) ~[embulk-core-0.9.17.jar:0.9.17]
	at com.treasuredata.worker.calls.EmbulkResult.run(EmbulkResult.java:115) ~[worker-bulkload-main-0.5.0.1954-1088894243adfcbb725069f34f38d5926a7fe3bd.jar:0.5.0.1954-1088894243adfcbb725069f34f38d5926a7fe3bd]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	Suppressed: java.lang.NullPointerException: null
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:463) ~[embulk-core-0.9.17.jar:0.9.17]
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:397) ~[embulk-core-0.9.17.jar:0.9.17]
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:394) ~[embulk-core-0.9.17.jar:0.9.17]
		at org.embulk.spi.Exec.doWith(Exec.java:22) ~[embulk-core-0.9.17.jar:0.9.17]
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:394) ~[embulk-core-0.9.17.jar:0.9.17]
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:181) ~[embulk-core-0.9.17.jar:0.9.17]
		... 8 common frames omitted
Caused by: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host {host_name}, named instance {instance_name} failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.begin(AbstractJdbcOutputPlugin.java:459) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:422) ~[na:na]
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:521) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:50) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:516) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.util.Filters.transaction(Filters.java:42) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:511) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:112) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.parser.msgpack.MsgpackParserPlugin.transaction(MsgpackParserPlugin.java:223) ~[na:na]
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:107) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.util.Decoders$RecursiveControl$1.run(Decoders.java:64) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.standards.GzipFileDecoderPlugin.transaction(GzipFileDecoderPlugin.java:25) ~[embulk-standards-0.9.17.jar:0.9.17]
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:60) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:29) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:105) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.input.s3.AbstractS3FileInputPlugin.resume(AbstractS3FileInputPlugin.java:152) ~[na:na]
	at org.embulk.input.s3.AbstractS3FileInputPlugin.transaction(AbstractS3FileInputPlugin.java:139) ~[na:na]
	at org.embulk.input.s3.TDS3FileInputPlugin.transaction(TDS3FileInputPlugin.java:18) ~[na:na]
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507) ~[embulk-core-0.9.17.jar:0.9.17]
	... 14 common frames omitted
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host {host_name}, named instance {instance_name} failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234) ~[na:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getInstancePort(SQLServerConnection.java:5919) ~[na:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.primaryPermissionCheck(SQLServerConnection.java:2347) ~[na:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2083) ~[na:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1950) ~[na:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1162) ~[na:na]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:735) ~[na:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_152]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_152]
	at org.embulk.output.sqlserver.SQLServerOutputConnector.connect(SQLServerOutputConnector.java:40) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputConnector.connect(AbstractJdbcOutputConnector.java:18) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.newConnection(AbstractJdbcOutputPlugin.java:314) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$2.run(AbstractJdbcOutputPlugin.java:449) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$RetryableSQLExecution.call(AbstractJdbcOutputPlugin.java:1284) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$RetryableSQLExecution.call(AbstractJdbcOutputPlugin.java:1272) ~[na:na]
	at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:81) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:62) ~[embulk-core-0.9.17.jar:0.9.17]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:1257) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:1249) ~[na:na]
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.begin(AbstractJdbcOutputPlugin.java:446) ~[na:na]
	... 35 common frames omitted
2019-08-14 12:47:23.780 +0000 [INFO] (pool-4-thread-1): Saving all buffers`

**Comment by hito4t** [comment]
@hieudion 
Are you using Azure SQL Database?
I couldn't find an instance name for Azure SQL Database.

**Comment by hito4t** [comment]
@hieudion 
It seems that JDBC URL is correct.
I think it is the problem of the environment, not of the plugin.

I tried to connect to SQL Server on the another machine, and couldn't connect by Microsoft JDBC Driver with an instance name (although I could connect by jTDS JDBC Driver with an instance name).

Following the error message, I started SQL Server Browser Service and allowed access by the UDP 1434 port, then I could connect.

Please check services on SQL Server machine and firewall settings.

**Comment by hieudion** [comment]
Thank alot for your hint. 
I will check and keep you update.

**Comment by hieudion** [comment]
@hito4t 
Sorry for the late update.  
I just found out the reason why `jTDS` can run fine using instance name but `mssql:jdbc` throw an exception.

In the code below, `jTDS` set the default port `1433` to the properties.
https://sourceforge.net/p/jtds/code/HEAD/tree/branches/jTDS%201.3%20(stable)/src/main/net/sourceforge/jtds/jdbc/Driver.java#l198

Then it comes to create a new connection by converting the instance name -> port
https://sourceforge.net/p/jtds/code/HEAD/tree/branches/jTDS%201.3%20(stable)/src/main/net/sourceforge/jtds/jdbc/MSSqlServerInfo.java#l55

Create a new connection
https://sourceforge.net/p/jtds/code/HEAD/tree/branches/jTDS%201.3%20(stable)/src/main/net/sourceforge/jtds/jdbc/JtdsConnection.java#l296

Because the port here is `1433` so the exception will not throw and it continues to run. Then successfully created a new connection with the instance in port `1433`, which has the same username + password with instance we intend to connect.

Should we implement the same logic as `jTDS` to keep back-ward compatible?
We can use the same way as `jTDS` in MSSqlServerInfo.java + retry 3 times with 2 second timeout 
https://sourceforge.net/p/jtds/code/HEAD/tree/branches/jTDS%201.3%20(stable)/src/main/net/sourceforge/jtds/jdbc/MSSqlServerInfo.java#l55
-> if it returns `TimeoutException` we try to connect to port `1433`.

**Comment by hito4t** [comment]
@hieudion 
Thank you for the information!

I think that is internal behavior of the JDBC Driver, and embulk shouldn't emulate the behavior.
If a user wish the behavior, he or she can achieve it by selecting jTDS Driver.

**Comment by hieudion** [comment]
@hito4t 
Agreed. 
Going to close this issue.
