### ISSUE TITLE
how to use variables in embulk-input-oracle

### ISSUE THREAD

**Issue by yester354** [embulk/embulk-input-jdbc#19]
Hi:
     in my last issues .frsyuki  give me an example about using variables in embulk-input-oracle.
and i tried without successed.my .yml.liquid file as below
   in:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.56
  user: sync
  password: m123
  database: oggmysql
  query: |
    select * from sync.ac where indate> ${last_record created_at}

last_record:
  created_at: "2015-03-01 00:00:00"

out:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.57
  user: flume
  password: m123
  database: embulk
  table: AC
  mode: insert
  insert_method: normal
  column_options:
               OWNER: {type: VARCHAR2(30)}
               OBJECT_NAME: {type: VARCHAR2(128)}
               SUBOBJECT_NAME: {type: VARCHAR2(30)}
               OBJECT_ID: {type: NUMBER}
               DATA_OBJECT_ID: {type: NUMBER}
           OBJECT_TYPE: {type: VARCHAR2(19)}
               CREATED: {type: DATE}
               LAST_DDL_TIME: {type: DATE}
               TIMESTAMP: {type: VARCHAR2(19)}
               STATUS: {type: VARCHAR2(7)}
               TEMPORARY: {type: VARCHAR2(1)}
               GENERATED: {type: VARCHAR2(1)}
               SECONDARY: {type: VARCHAR2(1)}
               NAMESPACE: {type: NUMBER}
               EDITION_NAME: {type: VARCHAR2(30)}

when i run embulk preview .it raise error as below
root@databus embulk-master]# embulk preview  var.yml.liquid 
2015-08-27 11:06:21.814 +0800: Embulk v0.7.2
2015-08-27 11:06:23.332 +0800 [INFO] (preview): Loaded plugin embulk-input-oracle (0.6.0)
java.lang.RuntimeException: java.sql.SQLException: Non supported SQL92 token at position: 38
        at com.google.common.base.Throwables.propagate(com/google/common/base/Throwables.java:160)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(org/embulk/input/jdbc/AbstractJdbcInputPlugin.java:144)
        at org.embulk.plugin.compat.InputPluginWrapper.transaction(org/embulk/plugin/compat/InputPluginWrapper.java:57)
        at org.embulk.exec.PreviewExecutor.doPreview(org/embulk/exec/PreviewExecutor.java:93)
        at org.embulk.exec.PreviewExecutor.access$000(org/embulk/exec/PreviewExecutor.java:27)
        at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:67)
        at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:63)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.PreviewExecutor.preview(org/embulk/exec/PreviewExecutor.java:63)
        at org.embulk.EmbulkEmbed.preview(org/embulk/EmbulkEmbed.java:168)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
        at RUBY.preview(/root/.embulk/bin/embulk!/embulk/runner.rb:35)
        at RUBY.run(/root/.embulk/bin/embulk!/embulk/command/embulk_run.rb:272)
        at RUBY.<top>(/root/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:940)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<top>(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:20)
Caused by: java.sql.SQLException: Non supported SQL92 token at position: 38
        at oracle.jdbc.driver.OracleSql.handleODBC(OracleSql.java:1275)
        at oracle.jdbc.driver.OracleSql.parse(OracleSql.java:1161)
        at oracle.jdbc.driver.OracleSql.getSql(OracleSql.java:328)
        at oracle.jdbc.driver.OracleSql.getSqlBytes(OracleSql.java:630)
        at oracle.jdbc.driver.T4CPreparedStatement.doDescribe(T4CPreparedStatement.java:818)
        at oracle.jdbc.driver.OracleStatement.describe(OracleStatement.java:3991)
        at oracle.jdbc.driver.OracleResultSetMetaData.<init>(OracleResultSetMetaData.java:55)
        at oracle.jdbc.driver.OraclePreparedStatement.getMetaData(OraclePreparedStatement.java:4357)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.getMetaData(OraclePreparedStatementWrapper.java:1503)
        at org.embulk.input.jdbc.JdbcInputConnection.getSchemaOfQuery(JdbcInputConnection.java:48)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.setupTask(AbstractJdbcInputPlugin.java:153)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:142)
        at org.embulk.plugin.compat.InputPluginWrapper.transaction(InputPluginWrapper.java:57)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:93)
        at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:27)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:67)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:63)
        at org.embulk.spi.Exec.doWith(Exec.java:25)
        at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:63)
        at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:457)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:318)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:114)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:321)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:198)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:184)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:201)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:116)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:103)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:32)
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
        at org.jruby.Ruby.runInterpreter(Ruby.java:837)
        at org.jruby.Ruby.loadFile(Ruby.java:2901)
        at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:245)
        at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:35)
        at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:895)
        at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:540)
        at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:425)
        at org.jruby.runtime.load.LoadService.require(LoadService.java:391)
        at org.jruby.RubyKernel.requireCommon(RubyKernel.java:947)
        at org.jruby.RubyKernel.require19(RubyKernel.java:940)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:364)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:198)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:184)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:201)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther74:require(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb)
        at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:599)
        at org.jruby.ir.Compiler$1.load(Compiler.java:111)
        at org.jruby.Ruby.runScript(Ruby.java:821)
        at org.jruby.Ruby.runScript(Ruby.java:813)
        at org.jruby.Ruby.runNormally(Ruby.java:751)
        at org.jruby.Ruby.runFromMain(Ruby.java:573)
        at org.jruby.Main.doRunFromMain(Main.java:403)
        at org.jruby.Main.internalRun(Main.java:298)
        at org.jruby.Main.run(Main.java:225)
        at org.jruby.Main.main(Main.java:197)
        at org.embulk.cli.Main.main(Main.java:20)

Error: java.sql.SQLException: Non supported SQL92 token at position: 38

Is there anything wrong in my yml file. and how to config the yml file to make last_record updated by ConfigDiff
thanks

**Comment by yester354** [comment]
Hi 
   by configing .yml.liquid file like this 
   config.yml.liquid:

in:
  type: oracle
  ...
  query: |
    SELECT id, name, created_at
    FROM table1
    WHERE created_at > timestamp '{{env.last_created_at}}'
    ORDER BY created_at
command:

$ export last_created_at="2015-01-01 00:00:00"
$ embulk config.yml.liquid

it works . but i dont know how to make the last_created_at variables updated by embulk

**Comment by frsyuki** [comment]
It seems liquid worked. closing.

You're using sort of scheduler to run embulk periodically, right? Such as cron. That scheduler starts a script. You can set last_created_at environment variable in the script.

**Comment by yester354** [comment]
@frsyuki 
 Hi .now my problem is the last_created_at can not be updated by embulk.so every time i need to set the variables by myself

**Comment by yester354** [comment]
@frsyuki 
yes  i use crontab to make embulk run periodically
