### ISSUE TITLE
[MySQL] `use_raw_query_with_incremental` option doesn't work properly if the incremental column doesn't exist in the first column.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-input-jdbc#215]
`use_raw_query_with_incremental` option doesn't work properly if the incremental column doesn't exist in the first column.

I think this issue doesn't relate to MySQL specifically.

## Environment

* embulk 0.9.23
* embulk-input-mysql: 0.12.1
* MySQL: 8.0.25

### Preparing data

```sql
create table table1 (
  id int primary key,
  name varchar(255) not null
);

insert into table1 values (1,'apple'), (2,'banana'), (3,'peach');

create table table2 (
  name varchar(255) not null,
  id int primary key
);

insert into table2 values ('apple',1), ('banana',2), ('peach',3);
```

```sql
mysql> select * from table1;
+----+--------+
| id | name   |
+----+--------+
|  1 | apple  |
|  2 | banana |
|  3 | peach  |
+----+--------+
3 rows in set (0.00 sec)

mysql> select * from table2;
+--------+----+
| name   | id |
+--------+----+
| apple  |  1 |
| banana |  2 |
| peach  |  3 |
+--------+----+
3 rows in set (0.00 sec)
```

## OK Case (table1)

```yaml
out:
  type: stdout

in:
  type: mysql
  database: embulk_test
  user: user
  password: passwd
  host: 127.0.0.1

  use_raw_query_with_incremental: true
  incremental_columns: [id]
  incremental: true
  last_record: [1]
  query: "select * from table1 where id > :id order by id"
#  query: "select * from table2 where id > :id order by id"

```

```
2021-06-03 22:18:02.449 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2021-06-03 22:18:06.066 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/user/.embulk/lib/gems"
2021-06-03 22:18:09.440 +0900 [INFO] (main): Started Embulk v0.9.23
2021-06-03 22:18:09.627 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-mysql (0.12.1)
2021-06-03 22:18:09.733 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2021-06-03 22:18:09.741 +0900 [INFO] (0001:transaction): JDBC Driver = /Users/user/.embulk/lib/gems/gems/embulk-input-mysql-0.12.1-java/default_jdbc_driver/mysql-connector-java-5.1.44.jar
2021-06-03 22:18:09.756 +0900 [INFO] (0001:transaction): Fetch size is 10000. Using server-side prepared statement.
2021-06-03 22:18:09.756 +0900 [INFO] (0001:transaction): Connecting to jdbc:mysql://127.0.0.1:3306/embulk_test options {useCompression=true, socketTimeout=1800000, useSSL=false, user=root, useLegacyDatetimeCode=false, tcpKeepAlive=true, useCursorFetch=true, connectTimeout=300000, password=***, zeroDateTimeBehavior=convertToNull}
2021-06-03 22:18:10.098 +0900 [INFO] (0001:transaction): Using JDBC Driver mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )
2021-06-03 22:18:10.099 +0900 [WARN] (0001:transaction): embulk-input-mysql 0.9.0 upgraded the bundled MySQL Connector/J version from 5.1.34 to 5.1.44 .
2021-06-03 22:18:10.099 +0900 [WARN] (0001:transaction): And set useLegacyDatetimeCode=false by default in order to get correct datetime value when the server timezone and the client timezone are different.
2021-06-03 22:18:10.099 +0900 [WARN] (0001:transaction): Set useLegacyDatetimeCode=true if you need to get datetime value same as older embulk-input-mysql.
2021-06-03 22:18:10.192 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2021-06-03 22:18:10.209 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2021-06-03 22:18:10.273 +0900 [WARN] (0017:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2021-06-03 22:18:10.273 +0900 [WARN] (0017:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2021-06-03 22:18:10.418 +0900 [INFO] (0017:task-0000): Fetch size is 10000. Using server-side prepared statement.
2021-06-03 22:18:10.421 +0900 [INFO] (0017:task-0000): Connecting to jdbc:mysql://127.0.0.1:3306/embulk_test options {useCompression=true, socketTimeout=1800000, useSSL=false, user=root, useLegacyDatetimeCode=false, tcpKeepAlive=true, useCursorFetch=true, connectTimeout=300000, password=***, zeroDateTimeBehavior=convertToNull}
2021-06-03 22:18:10.443 +0900 [INFO] (0017:task-0000): SQL: select * from table1 where id > ? order by id
2021-06-03 22:18:10.449 +0900 [INFO] (0017:task-0000): Parameters: [1]
2021-06-03 22:18:10.465 +0900 [INFO] (0017:task-0000): > 0.01 seconds
2,banana
3,peach
2021-06-03 22:18:10.495 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2021-06-03 22:18:10.510 +0900 [INFO] (main): Committed.
2021-06-03 22:18:10.510 +0900 [INFO] (main): Next config diff: {"in":{"last_record":[3]},"out":{}}
```

## NG Case (table2)

```yaml
out:
  type: stdout

in:
  type: mysql
  database: embulk_test
  user: user
  password: passwd
  host: 127.0.0.1

  use_raw_query_with_incremental: true
  incremental_columns: [id]
  incremental: true
  last_record: [1]
#  query: "select * from table1 where id > :id order by id"
  query: "select * from table2 where id > :id order by id"
```

```
org.embulk.exec.PartialExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
	at org.embulk.cli.Main.main(Main.java:64)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:463)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:397)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:394)
		at org.embulk.spi.Exec.doWith(Exec.java:22)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:394)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:245)
		... 5 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.embulk.input.jdbc.JdbcInputConnection.replacePlaceholder(JdbcInputConnection.java:400)
	at org.embulk.input.jdbc.JdbcInputConnection.wrapIncrementalQuery(JdbcInputConnection.java:304)
	at org.embulk.input.jdbc.AbstractJdbcInputPlugin.setupTask(AbstractJdbcInputPlugin.java:302)
	at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:223)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
	... 11 more
  ```

**Comment by y-ken** [comment]
I know this is kind of tricky behavior.
since the beginning of adding this feature, the select order is the known limitation issue.
we have to put incremental column in the top of the select clause.
https://github.com/embulk/embulk-input-jdbc/pull/143#issuecomment-407293849

**Comment by hiroyuki-sato** [comment]
This issue was the known issue. I needed to set column names explicitly.
And also incremental columns have to locate at the beginning of the select clause.

| select            | result |
|-------------------|--------|
| `select id,name`  | OK     |
| `select name,id`  | NG     |
| `select *`        | NG     |

@y-ken, Thannk you!
