### ISSUE TITLE
Java Optional error

### ISSUE THREAD

**Issue by lance-edmodo** [embulk/embulk-input-jdbc#52]
After several weeks of running correctly, we just now got this stack trace. Any hints as to how to fix this?

2016-06-16 01:30:42.808 +0000 [INFO] (0001:transaction): Loaded plugin embulk-input-mysql (0.7.1)
2016-06-16 01:30:43.017 +0000 [INFO] (0001:transaction): Loaded plugin embulk-output-redshift (0.5.1)
2016-06-16 01:30:43.083 +0000 [INFO] (0001:transaction): Fetch size is 10000. Using server-side prepared statement.
2016-06-16 01:30:43.472 +0000 [INFO] (0001:transaction): SQL: select * from zendmodo.profiles where creation_date between '2016-06-15 00:00:00' and '2016-06-15 23:59:59' OR modified_date between '2016-06-15 00:00:00' and '2016-06-15 23:59:59'
2016-06-16 01:30:43.606 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2016-06-16 01:30:43.667 +0000 [INFO] (0001:transaction): Connecting to jdbc:postgresql://redshift-analytics.nodemodo.com:5439/dev options {user=root, loglevel=2, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2016-06-16 01:30:43.772 +0000 [INFO] (0001:transaction): SQL: SET search_path TO "zzz"
2016-06-16 01:30:43.797 +0000 [INFO] (0001:transaction): > 0.02 seconds
2016-06-16 01:30:43.798 +0000 [INFO] (0001:transaction): Using insert mode
2016-06-16 01:30:43.873 +0000 [INFO] (0001:transaction): SQL: DROP TABLE IF EXISTS "tmp_2016061_206cc800_bl_tmp000"
2016-06-16 01:30:44.263 +0000 [INFO] (0001:transaction): > 0.39 seconds
2016-06-16 01:32:14.647 +0000 [INFO] (0001:transaction): SQL: CREATE TABLE IF NOT EXISTS "tmp_2016061_206cc800_bl_tmp000" ("user_id" BIGINT, "gender" VARCHAR(65535), "country_id" VARCHAR(65535), "avatar_type" VARCHAR(65535), "avatar_format" VARCHAR(65535), "default_avatar_name" VARCHAR(65535), "school_other" VARCHAR(65535), "creation_date" TIMESTAMP, "code_verified" BOOLEAN, "district_id" BIGINT, "school_id" BIGINT, "admin_rights" VARCHAR(65535), "about" VARCHAR(65535), "start_level_id" BIGINT, "end_level_id" BIGINT, "verified" BOOLEAN, "parent_code" VARCHAR(65535), "publisher_suggest" BOOLEAN, "donors_choose" BIGINT, "modified_date" TIMESTAMP, "vanity" VARCHAR(65535), "avatar_num" BIGINT, "secondary_theme_enabled" BOOLEAN, "date_of_birth" TIMESTAMP)
2016-06-16 01:32:14.658 +0000 [INFO] (0001:transaction): > 0.01 seconds
2016-06-16 01:33:09.833 +0000 [INFO] (0001:transaction): SQL: DROP TABLE IF EXISTS "tmp_2016061_206cc800_bl_tmp001"
2016-06-16 01:33:09.837 +0000 [INFO] (0001:transaction): > 0.00 seconds
2016-06-16 01:33:33.951 +0000 [INFO] (0001:transaction): SQL: CREATE TABLE IF NOT EXISTS "tmp_2016061_206cc800_bl_tmp001" ("user_id" BIGINT, "gender" VARCHAR(65535), "country_id" VARCHAR(65535), "avatar_type" VARCHAR(65535), "avatar_format" VARCHAR(65535), "default_avatar_name" VARCHAR(65535), "school_other" VARCHAR(65535), "creation_date" TIMESTAMP, "code_verified" BOOLEAN, "district_id" BIGINT, "school_id" BIGINT, "admin_rights" VARCHAR(65535), "about" VARCHAR(65535), "start_level_id" BIGINT, "end_level_id" BIGINT, "verified" BOOLEAN, "parent_code" VARCHAR(65535), "publisher_suggest" BOOLEAN, "donors_choose" BIGINT, "modified_date" TIMESTAMP, "vanity" VARCHAR(65535), "avatar_num" BIGINT, "secondary_theme_enabled" BOOLEAN, "date_of_birth" TIMESTAMP)
2016-06-16 01:33:33.972 +0000 [INFO] (0001:transaction): > 0.02 seconds
2016-06-16 01:34:16.513 +0000 [INFO] (0001:transaction): SQL: DROP TABLE IF EXISTS "tmp_2016061_206cc800_bl_tmp002"
2016-06-16 01:34:24.281 +0000 [INFO] (0001:transaction): > 7.77 seconds
2016-06-16 01:35:07.459 +0000 [INFO] (0001:transaction): SQL: CREATE TABLE IF NOT EXISTS "tmp_2016061_206cc800_bl_tmp002" ("user_id" BIGINT, "gender" VARCHAR(65535), "country_id" VARCHAR(65535), "avatar_type" VARCHAR(65535), "avatar_format" VARCHAR(65535), "default_avatar_name" VARCHAR(65535), "school_other" VARCHAR(65535), "creation_date" TIMESTAMP, "code_verified" BOOLEAN, "district_id" BIGINT, "school_id" BIGINT, "admin_rights" VARCHAR(65535), "about" VARCHAR(65535), "start_level_id" BIGINT, "end_level_id" BIGINT, "verified" BOOLEAN, "parent_code" VARCHAR(65535), "publisher_suggest" BOOLEAN, "donors_choose" BIGINT, "modified_date" TIMESTAMP, "vanity" VARCHAR(65535), "avatar_num" BIGINT, "secondary_theme_enabled" BOOLEAN, "date_of_birth" TIMESTAMP)
2016-06-16 01:35:08.085 +0000 [INFO] (0001:transaction): > 0.63 seconds
2016-06-16 01:36:10.478 +0000 [INFO] (0001:transaction): SQL: DROP TABLE IF EXISTS "tmp_2016061_206cc800_bl_tmp003"
2016-06-16 01:36:10.864 +0000 [INFO] (0001:transaction): > 0.39 seconds
2016-06-16 01:36:37.078 +0000 [INFO] (0001:transaction): SQL: CREATE TABLE IF NOT EXISTS "tmp_2016061_206cc800_bl_tmp003" ("user_id" BIGINT, "gender" VARCHAR(65535), "country_id" VARCHAR(65535), "avatar_type" VARCHAR(65535), "avatar_format" VARCHAR(65535), "default_avatar_name" VARCHAR(65535), "school_other" VARCHAR(65535), "creation_date" TIMESTAMP, "code_verified" BOOLEAN, "district_id" BIGINT, "school_id" BIGINT, "admin_rights" VARCHAR(65535), "about" VARCHAR(65535), "start_level_id" BIGINT, "end_level_id" BIGINT, "verified" BOOLEAN, "parent_code" VARCHAR(65535), "publisher_suggest" BOOLEAN, "donors_choose" BIGINT, "modified_date" TIMESTAMP, "vanity" VARCHAR(65535), "avatar_num" BIGINT, "secondary_theme_enabled" BOOLEAN, "date_of_birth" TIMESTAMP)
2016-06-16 01:36:37.320 +0000 [INFO] (0001:transaction): > 0.24 seconds
org.embulk.exec.PartialExecutionException: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:363)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:572)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:374)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:370)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:370)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at RUBY.run(/opt/embulk/bin/embulk!/embulk/runner.rb:84)
	at RUBY.run(/opt/embulk/bin/embulk!/embulk/command/embulk_run.rb:306)
	at RUBY.<top>(/opt/embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:937)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at opt.embulk.bin.embulk.embulk.command.embulk_bundle.<top>(file:/opt/embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:479)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:410)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:406)
		at org.embulk.spi.Exec.doWith(Exec.java:25)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:406)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:184)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:452)
		at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:313)
		at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:140)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:126)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
		at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
		at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:414)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:348)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:210)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:196)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
		at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
		at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
		at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
		at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
		at org.jruby.Ruby.runInterpreter(Ruby.java:833)
		at org.jruby.Ruby.loadFile(Ruby.java:2905)
		at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:235)
		at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
		at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:900)
		at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:541)
		at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:426)
		at org.jruby.runtime.load.LoadService.require(LoadService.java:392)
		at org.jruby.RubyKernel.requireCommon(RubyKernel.java:944)
		at org.jruby.RubyKernel.require19(RubyKernel.java:937)
		at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
		at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:380)
		at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:210)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:196)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
		at opt.embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/opt/embulk/bin/embulk!/embulk/command/embulk_bundle.rb)
		at opt.embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/opt/embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
		at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
		at org.jruby.ir.Compiler$1.load(Compiler.java:111)
		at org.jruby.Ruby.runScript(Ruby.java:817)
		at org.jruby.Ruby.runScript(Ruby.java:809)
		at org.jruby.Ruby.runNormally(Ruby.java:747)
		at org.jruby.Ruby.runFromMain(Ruby.java:569)
		at org.jruby.Main.doRunFromMain(Main.java:415)
		at org.jruby.Main.internalRun(Main.java:310)
		at org.jruby.Main.run(Main.java:239)
		at org.jruby.Main.main(Main.java:201)
		at org.embulk.cli.Main.main(Main.java:23)
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.doBegin(AbstractJdbcOutputPlugin.java:481)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$1.run(AbstractJdbcOutputPlugin.java:362)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:966)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:963)
	at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:100)
	at org.embulk.spi.util.RetryExecutor.runInterruptible(R
[2016-06-16 01:38:21,544] {EmbulkWSPlugin.py:82} INFO - etryExecutor.java:77)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:963)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:952)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.begin(AbstractJdbcOutputPlugin.java:357)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:326)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:529)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:54)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:524)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
	at org.embulk.spi.util.Filters.transaction(Filters.java:49)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:518)
	at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:163)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:513)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:374)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:370)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:370)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:452)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:313)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:140)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:126)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:414)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:348)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:210)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:196)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:833)
	at org.jruby.Ruby.loadFile(Ruby.java:2905)
	at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:235)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:900)
	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:541)
	at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:426)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:392)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:944)
	at org.jruby.RubyKernel.require19(RubyKernel.java:937)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:380)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:210)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:196)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at opt.embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/opt/embulk/bin/embulk!/embulk/command/embulk_bundle.rb)
	at opt.embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/opt/embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.jruby.ir.Compiler$1.load(Compiler.java:111)
	at org.jruby.Ruby.runScript(Ruby.java:817)
	at org.jruby.Ruby.runScript(Ruby.java:809)
	at org.jruby.Ruby.runNormally(Ruby.java:747)
	at org.jruby.Ruby.runFromMain(Ruby.java:569)
	at org.jruby.Main.doRunFromMain(Main.java:415)
	at org.jruby.Main.internalRun(Main.java:310)
	at org.jruby.Main.run(Main.java:239)
	at org.jruby.Main.main(Main.java:201)
	at org.embulk.cli.Main.main(Main.java:23)

Error: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value

**Comment by hito4t** [comment]
Hi

It seems that embulk-output-jdbc couldn't create temporary table for loading.

- Can you check if the table "tmp_2016061_206cc800_bl_tmp000" exists in Redshift?
- Did any other program accessing Redshift run at the same time?

**Comment by bcipolli** [comment]
I am hitting this same issue on redshift.

* The table doesn't exist, but is created after the code executes.
* No other program is accessing redshift at the same time.

I don't have this issue with other inputs, either. `MySql` and `Mongo` inputs work great.

Any help is appreciated!

**Comment by hiroyuki-sato** [comment]
Maybe this is embulk-output-redshift issue.
https://github.com/embulk/embulk-output-jdbc/issues/168.

Redshift doesn't support uppercase table name.
