### ISSUE TITLE
embulk-input-postgresql: Column type 'timestamp' set at incremental_columns option is not supported

### ISSUE THREAD

**Issue by hbadmin** [embulk/embulk-input-jdbc#97]
I got following error with `embulk run config.yml`. 
```
org.embulk.exec.PartialExecutionException: org.embulk.spi.DataException: Column type 'timestamp' set at incremental_columns option is not supported
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
        at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
        at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
        at RUBY.run(/home/dev/.embulk/bin/embulk!/embulk/runner.rb:84)
        at RUBY.run(/home/dev/.embulk/bin/embulk!/embulk/command/embulk_run.rb:307)
        at RUBY.<main>(/home/dev/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
        at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
        at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
        at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at home.dev.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(home/dev/$_dot_embulk/bin/embulk/embulk/command/file:/home/dev/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at home.dev.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/home/dev/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
        at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
        at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
        at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
        at org.jruby.Main.internalRun(org/jruby/Main.java:313)
        at org.jruby.Main.run(org/jruby/Main.java:242)
        at org.jruby.Main.main(org/jruby/Main.java:204)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: org.embulk.spi.DataException: Column type 'timestamp' set at incremental_columns option is not supported
        at org.embulk.input.jdbc.getter.AbstractColumnGetter.encodeToJson(AbstractColumnGetter.java:92)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin$LastRecordStore.accept(AbstractJdbcInputPlugin.java:383)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.run(AbstractJdbcInputPlugin.java:432)
        at org.embulk.spi.util.Executors.process(Executors.java:67)
        at org.embulk.spi.util.Executors.process(Executors.java:42)
        at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:184)
        at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:180)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Error: org.embulk.spi.DataException: Column type 'timestamp' set at incremental_columns option is not supported
```

`embulk preview config.yml` has no error.
```
2017-02-08 20:15:44.035 +0900: Embulk v0.8.16
2017-02-08 20:15:45.633 +0900 [INFO] (0001:preview): Loaded plugin embulk-input-postgresql (0.8.0)
2017-02-08 20:15:45.863 +0900 [INFO] (0001:preview): SQL: SET search_path TO "public"
2017-02-08 20:15:45.979 +0900 [INFO] (0001:preview): SQL: SET search_path TO "public"
2017-02-08 20:15:45.982 +0900 [INFO] (0001:preview): SQL: DECLARE cur NO SCROLL CURSOR FOR SELECT * FROM (SELECT A, B, C, ... FROM "XXXXXXXX") embulk_incremental_ ORDER BY "G"
2017-02-08 20:15:45.986 +0900 [INFO] (0001:preview): SQL: FETCH FORWARD 10000 FROM cur
2017-02-08 20:15:46.035 +0900 [INFO] (0001:preview): > 0.05 seconds
(snip)
```

config.yml
```
in:
  type: postgresql
  host: ...
  port: 5432
  user: ...
  password: ...
  database: ...
  table: XXXXXXXX
  select: "A, B, C, ..."
  incremental: true
  incremental_columns: [G]
  default_timezone: "+0900"
out:
  type: td
  apikey: ...
  endpoint: ...
  database: ...
  table: XXXXXXXX
  time_column: G
  default_timezone: "+0900"
```

## Environment

* CentOS Linux release 7.2.1511 (Core)
* PostgreSQL 9.2.15-1.el7_2 (bundled with centos)
* EmBulk 0.8.16

PostgreSQL
```
psql> \d XXXXXXX
           テーブル "public.XXXXXXXX"
         列         |             型              |  修飾語
--------------------+-----------------------------+----------
 A                  | bigint                      | not null
 B                  | character varying(16)       | not null
 C                  | character(8)                | not null
 D                  | character(1)                |
 E                  | character(7)                |
 F                  | character(7)                |
 G                  | timestamp without time zone |
 H                  | character varying(15)       |
インデックス:
    "XXXXXXXX_pkey" PRIMARY KEY, btree (A, B, C)
```

embulk gem list
```
2017-02-08 20:06:42.746 +0900: Embulk v0.8.16

*** LOCAL GEMS ***

did_you_mean (default: 1.0.1)
embulk-input-postgresql (0.8.0)
embulk-output-td (0.3.12)
jar-dependencies (default: 0.3.5)
jruby-openssl (0.9.17 java)
json (1.8.3 java)
minitest (default: 5.4.1)
net-telnet (default: 0.1.1)
power_assert (default: 0.2.3)
psych (2.0.17 java)
racc (1.4.14 java)
rake (default: 10.4.2)
rdoc (default: 4.2.0)
test-unit (default: 3.1.1)
```

**Comment by hbadmin** [comment]
I have learned that it has not been released the version supported postgresql timestamp yet.
close.

**Comment by hito4t** [comment]
Now I am preparing to release.
Please wait for a few days.
